### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ghost** [Atry/memcontinuationed#1]
if I add addCompilerPlugin("org.scala-lang.plugins" % "continuations" % "2.10.2") in my build.scala, I have this error : 
java.lang.NoClassDefFoundError: scala/reflect/internal/AnnotationCheckers$AnnotationChecker
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2404)
...
Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.AnnotationCheckers$AnnotationChecker
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
...
[error](compile:compile) java.lang.reflect.InvocationTargetException

But if I change the version of this plugin to 2.9.2, I don't have this error but I have some errors in my code because not found method require, add get etc (probably because scala 2.9.2)

Application has build with sbt 1.12.4 and scala 2.10.2
